name: Keep Glitch Alive

on:
  schedule:
    - cron: '*/10 11-14 * * *'
    - cron: '*/10 19-22 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar hora de ejecucion
        run: date
      - name: Curl to Glitch API
        run: curl -s https://spezia.glitch.me/ping
