name: Keep Glitch Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # cada 10 minutos
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl to Glitch API
        run: curl -s https://tu-api.glitch.me/ping
