name: Keep Glitch Alive

on:
  schedule:
    - cron: '*/10 14-17 * * *'  # 11:00 a 14:59 hora Argentina (UTC 14-17) 
    - cron: '*/10 22-23 * * *'  # 19:00 a 20:59 hora Argentina (UTC 22-23) 
    - cron: '*/10 0-1 * * *'    # 21:00 a 22:59 hora Argentina (UTC 00-01) 
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl to Glitch API
        run: curl -s https://spezia.glitch.me/ping
