name: Keep Glitch Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Cada 10 minutos
  workflow_dispatch:       # Permite ejecutarlo manualmente

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl to Glitch API
        run: curl -s https://spezia.glitch.me/ping
