name: Keep Glitch Alive

on:
  schedule:
    - cron: '*/5 14-16 * * *'  # de 11:00 a 13:59
    - cron: '*/5 22-23 * * *'  # de 19:00 a 20:59
    - cron: '*/5 0-2 * * *'    # de 21:00 a 23:59
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar hora de ejecucion
        run: date
      - name: Curl to Glitch API
        run: curl -s https://spezia.glitch.me/
